import Aboutus from '@/components/Aboutus'
import Footer from '@/components/common/Footer'
import Header from '@/components/common/Header'
import Head from 'next/head'
import React from 'react'

export default function about() {
  return (
    <div>
       <Head>
        <title>ABOUT US | The Yummy Motion</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo.png" />
      </Head>
      <main>
      <Header/>
      <Aboutus/>
      <Footer/>

      </main>
    </div>
  )
}
