import Footer from '@/components/common/Footer'
import Header from '@/components/common/Header'
import Opening from '@/components/Home/Opening'
import Head from 'next/head'
import React from 'react'

function Openinghours() {
  return (
    <div>
         <Head>
                <title>OPENING HOURS | THE YUMMY MOTION</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/images/logo.png" />
            </Head>
            <main>
                <Header />
                <Opening />
                <Footer />

            </main>
    </div>
  )
}

export default Openinghours